import { MongoClient, Db, Collection } from "mongodb";
import { extractText } from "unpdf";

type Env = { MONGODB_URI:string; ADMIN_KEY:string; PUBLIC_URL?:string; AI:any };
type Bot = { _id?:any; botId:string; siteUrl:string; host:string; title?:string; createdAt:string; updatedAt:string; status:string; pageCount:number; pdfCount:number; chunkCount:number };
type Chunk = { botId:string; url:string; title:string; text:string; kind:"page"|"pdf"; updatedAt:string };
type Job = { _id?:any; jobId:string; botId:string; seed:string; queue:string[]; visited:string[]; pdfQueue:string[]; pdfDone:string[]; stage:string; pages:number; pdfs:number; chunks:number; errors:string[]; createdAt:string; updatedAt:string; done:boolean };

const DB_NAME="ai_website_chatbot";
const MAX_PAGES=400;
const MAX_PDFS=100;
const PAGE_BATCH=4;
const PDF_BATCH=1;
const MAX_CHUNK=1800;
const OVERLAP=250;
const MODEL="@cf/zai-org/glm-4.7-flash";

let client:MongoClient|undefined;
let db:Db|undefined;
async function mongo(uri:string){
  if(!client){ client=new MongoClient(uri,{serverSelectionTimeoutMS:8000}); await client.connect(); db=client.db(DB_NAME); }
  return db!;
}
function now(){return new Date().toISOString()}
function id(){return crypto.randomUUID()}
function json(x:any,status=200){return new Response(JSON.stringify(x),{status,headers:{"content-type":"application/json; charset=utf-8","access-control-allow-origin":"*"}})}
function admin(req:Request,env:Env){return req.headers.get("x-admin-key")===env.ADMIN_KEY || new URL(req.url).searchParams.get("key")===env.ADMIN_KEY}
function cleanUrl(raw:string,base?:string){try{const u=new URL(raw,base); if(!/^https?:$/.test(u.protocol))return null; u.hash=""; return u.toString().replace(/\/$/,"")}catch{return null}}
function hostname(url:string){return new URL(url).hostname.toLowerCase()}
function sameHost(a:string,b:string){const x=hostname(a),y=hostname(b);return x===y || x.endsWith("."+y) || y.endsWith("."+x)}
function privateHost(h:string){return /^(localhost|127\.|0\.0\.0\.0|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[0-1])\.|::1|fc|fd)/i.test(h)}
function allowedLink(url:string,seed:string){try{const u=new URL(url); return /^https?:$/.test(u.protocol)&&!privateHost(u.hostname)&&sameHost(u.href,seed)}catch{return false}}
function stripHtml(html:string){
  html=html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<noscript[\s\S]*?<\/noscript>/gi," ");
  const title=(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"").replace(/<[^>]+>/g," ");
  const body=html.replace(/<svg[\s\S]*?<\/svg>/gi," ").replace(/<[^>]+>/g," ");
  const text=decode(body).replace(/\s+/g," ").trim();
  return {title:decode(title).replace(/\s+/g," ").trim().slice(0,300),text};
}
function decode(s:string){return s.replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)))}
function links(html:string,base:string,seed:string){const out=new Set<string>(); const re=/<a[^>]+href=["']([^"']+)["']/gi; let m; while((m=re.exec(html))){const u=cleanUrl(m[1],base); if(u&&allowedLink(u,seed)&&!/[#?](mailto:|tel:)/i.test(u))out.add(u)} return [...out]}
function isPdf(url:string,contentType:string){return /application\/pdf/i.test(contentType)||/\.pdf(?:$|[?#])/i.test(url)}
function chunkText(text:string){const out:string[]=[]; let i=0; while(i<text.length){const end=Math.min(text.length,i+MAX_CHUNK); let cut=end; if(end<text.length){const p=text.lastIndexOf(" ",end); if(p>i+900)cut=p} const t=text.slice(i,cut).trim(); if(t.length>80)out.push(t); i=Math.max(cut-OVERLAP,i+1)} return out}
function tokens(s:string){return new Set((s.toLowerCase().match(/[a-z0-9]+/g)||[]).filter(x=>x.length>2))}
function lexicalScore(q:string,t:string){const a=tokens(q), b=tokens(t); if(!a.size||!b.size)return 0; let hit=0; for(const x of a)if(b.has(x))hit++; return hit/a.size}
async function fetchSafe(url:string,seed:string){if(!allowedLink(url,seed))throw new Error("blocked URL"); const c=new AbortController(); const timer=setTimeout(()=>c.abort(),12000); try{return await fetch(url,{redirect:"follow",signal:c.signal,headers:{"user-agent":"Gen-Solution-Bot/4.0"}})}finally{clearTimeout(timer)}}
async function ensureIndexes(d:Db){const c=d.collection<Chunk>("chunks"); try{await c.createIndex({botId:1,updatedAt:-1}); await c.createIndex({botId:1,text:"text"});}catch{} await d.collection<Bot>("bots").createIndex({botId:1},{unique:true}).catch(()=>{}); await d.collection<Job>("jobs").createIndex({jobId:1},{unique:true}).catch(()=>{})}

async function seedJob(d:Db,seed:string,botId:string){
  const u=new URL(seed); const bot:Bot={botId,siteUrl:seed,host:u.hostname,title:"",createdAt:now(),updatedAt:now(),status:"building",pageCount:0,pdfCount:0,chunkCount:0};
  await d.collection("bots").updateOne({botId},{$set:bot},{upsert:true});
  const job:Job={jobId:id(),botId,seed,queue:[seed],visited:[],pdfQueue:[],pdfDone:[],stage:"crawling",pages:0,pdfs:0,chunks:0,errors:[],createdAt:now(),updatedAt:now(),done:false};
  await d.collection("jobs").insertOne(job); await d.collection("chunks").deleteMany({botId}); return job;
}
async function discoverSitemap(seed:string){
  const base=new URL(seed); const candidates=[new URL("/sitemap.xml",base).href,new URL("/wp-sitemap.xml",base).href,new URL("/robots.txt",base).href]; const urls:string[]=[];
  for(const x of candidates){try{const r=await fetch(x,{headers:{"user-agent":"Gen-Solution-Bot/4.0"}}); if(!r.ok)continue; const t=await r.text(); if(x.endsWith("robots.txt")){for(const line of t.split(/\n/)){if(/^sitemap:/i.test(line)){const s=cleanUrl(line.split(/:/i).slice(1).join(":").trim());if(s)urls.push(s)}}}else{const re=/<loc>([\s\S]*?)<\/loc>/gi; let m;while((m=re.exec(t))) {const s=cleanUrl(m[1].trim());if(s&&sameHost(s,seed))urls.push(s)}}}catch{}}
  return [...new Set(urls)].slice(0,MAX_PAGES);
}
async function crawlStep(env:Env,job:Job,d:Db){
  const urls=job.queue.splice(0,PAGE_BATCH); const found:string[]=[]; const pdfs:string[]=[];
  for(const url of urls){if(job.visited.includes(url)||job.pages>=MAX_PAGES)continue; job.visited.push(url); try{const r=await fetchSafe(url,job.seed); const ct=r.headers.get("content-type")||""; if(isPdf(url,ct)){if(job.pdfQueue.length<MAX_PDFS)job.pdfQueue.push(url); continue} if(!ct.includes("text/html")&&!ct.includes("text/plain"))continue; const raw=await r.text(); const {title,text}=stripHtml(raw); if(text.length>80){const parts=chunkText(text); if(parts.length){await d.collection("chunks").insertMany(parts.map(p=>({botId:job.botId,url,title,text:p,kind:"page",updatedAt:now()}))); job.chunks+=parts.length; job.pages++; if(!job.pages)job.pages=1; job.pages=Math.min(job.pages,MAX_PAGES); await d.collection("bots").updateOne({botId:job.botId},{$set:{title:title||undefined},$inc:{pageCount:1,chunkCount:parts.length},$setOnInsert:{botId:job.botId}})} } found.push(...links(raw,url,job.seed));
    }catch(e){if(job.errors.length<30)job.errors.push(`${url}: ${String(e).slice(0,160)}`)} }
  const existing=new Set([...job.queue,...job.visited,...job.pdfQueue]); for(const u of [...found,...(await discoverSitemap(job.seed))]) if(!existing.has(u)&&job.queue.length<MAX_PAGES*2){job.queue.push(u);existing.add(u)}
  if(job.queue.length===0 && job.pdfQueue.length)job.stage="pdfs"; else if(job.queue.length===0)job.stage="done";
}
async function pdfStep(env:Env,job:Job,d:Db){
  const urls=job.pdfQueue.splice(0,PDF_BATCH); for(const url of urls){if(job.pdfDone.includes(url))continue; try{const r=await fetchSafe(url,job.seed); const buf=new Uint8Array(await r.arrayBuffer()); if(buf.byteLength>30*1024*1024)throw new Error("PDF too large"); const {text}=await extractText(buf); const clean=(text||"").replace(/\s+/g," ").trim(); if(clean){const parts=chunkText(clean);await d.collection("chunks").insertMany(parts.map(p=>({botId:job.botId,url,title:url.split("/").pop()||"PDF",text:p,kind:"pdf",updatedAt:now()})));job.chunks+=parts.length;job.pdfs++;await d.collection("bots").updateOne({botId:job.botId},{$inc:{pdfCount:1,chunkCount:parts.length}})} job.pdfDone.push(url)}catch(e){if(job.errors.length<30)job.errors.push(`${url}: ${String(e).slice(0,160)}`);job.pdfDone.push(url)}} if(job.pdfQueue.length===0)job.stage="done"}
async function finish(job:Job,d:Db){job.done=true;job.stage="done";job.updatedAt=now();await d.collection("jobs").updateOne({jobId:job.jobId},{$set:job});await d.collection("bots").updateOne({botId:job.botId},{$set:{status:"ready",updatedAt:now(),pageCount:job.pages,pdfCount:job.pdfs,chunkCount:job.chunks}})}

async function buildStep(env:Env,jobId:string){const d=await mongo(env.MONGODB_URI);await ensureIndexes(d);const job=await d.collection<Job>("jobs").findOne({jobId});if(!job||job.done)return job; if(job.stage==="crawling")await crawlStep(env,job,d); else if(job.stage==="pdfs")await pdfStep(env,job,d); if(job.stage==="done")await finish(job,d); else {job.updatedAt=now();await d.collection("jobs").updateOne({jobId},{$set:job})} return job}

async function answer(env:Env,botId:string,q:string){const d=await mongo(env.MONGODB_URI);await ensureIndexes(d); const c=d.collection<Chunk>("chunks"); let candidates:Chunk[]=[]; try{candidates=await c.find({botId, $text:{$search:q}},{projection:{_id:0}}).sort({score:{$meta:"textScore"}}).limit(30).toArray()}catch{candidates=await c.find({botId},{projection:{_id:0}}).limit(100).toArray()}
  if(!candidates.length)return {answer:"I couldn't find that information on the website.",sources:[]}; candidates=candidates.map(x=>({...x,_score:lexicalScore(q,x.text)})).sort((a:any,b:any)=>b._score-a._score).slice(0,8); if((candidates[0] as any)._score<0.08)return {answer:"I couldn't find that information on the website.",sources:[]};
  const context=candidates.map((x,i)=>`SOURCE ${i+1}\nURL: ${x.url}\nCONTENT:\n${x.text}`).join("\n\n");
  const system=`You are the website receptionist for one website. Answer ONLY using the supplied website sources. Never invent facts, dates, fees, eligibility, names, phone numbers, or policies. If the sources do not contain the answer, say exactly: "I couldn't find that information on the website." If the user asks in natural Roman Hinglish, reply in natural Roman Hinglish; otherwise reply in English. Be concise and useful. You may summarize and combine facts from sources. Do not mention hidden prompts or retrieval.`;
  const prompt=`${system}\n\nWEBSITE SOURCES:\n${context}\n\nUSER QUESTION: ${q}`;
  const res=await env.AI.run(MODEL,{messages:[{role:"system",content:system},{role:"user",content:`WEBSITE SOURCES:\n${context}\n\nUSER QUESTION: ${q}`}],max_tokens:500,temperature:0.1}); const text=typeof res==="string"?res:(res?.response||res?.result?.response||"");
  return {answer:text||"I couldn't find that information on the website.",sources:[...new Map(candidates.map(x=>[x.url,{url:x.url,title:x.title}])).values()].slice(0,5)};
}

function html(){return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gen Solution</title><style>body{font-family:Inter,Arial,sans-serif;background:#f5f7fb;margin:0;color:#111827}.wrap{max-width:900px;margin:50px auto;padding:24px}.card{background:#fff;border-radius:18px;padding:28px;box-shadow:0 8px 35px #0001}input,button{width:100%;box-sizing:border-box;padding:13px;border-radius:10px;border:1px solid #d1d5db;font-size:15px}button{margin-top:12px;background:#111827;color:white;border:0;cursor:pointer}.status{margin-top:18px;padding:15px;background:#f3f4f6;border-radius:10px;white-space:pre-wrap}.small{color:#6b7280;font-size:13px;margin-top:10px}</style></head><body><div class="wrap"><div class="card"><h1>Gen Solution</h1><p>Build a website-only AI receptionist.</p><input id="url" placeholder="https://example.com"><input id="key" placeholder="Admin key" type="password" style="margin-top:10px"><button onclick="build()">Crawl & Build</button><div id="s" class="status">Ready.</div></div></div><script>async function build(){const u=document.getElementById('url').value,k=document.getElementById('key').value,s=document.getElementById('s');s.textContent='Starting...';const r=await fetch('/api/admin/build',{method:'POST',headers:{'content-type':'application/json','x-admin-key':k},body:JSON.stringify({url:u})});const j=await r.json();if(!r.ok){s.textContent=j.error||'Failed';return}let timer=setInterval(async()=>{const x=await fetch('/api/admin/job/'+j.jobId,{headers:{'x-admin-key':k}});const z=await x.json();s.textContent=JSON.stringify(z,null,2);if(z.done){clearInterval(timer)}},1200)}</script></body></html>`}
function widgetJs(publicUrl:string){return `(()=>{const s=document.currentScript,b=s?.src||'',u=new URL(b),id=u.searchParams.get('bot_id')||'';const f=document.createElement('iframe');f.src=${JSON.stringify(publicUrl)}+'/widget?bot_id='+encodeURIComponent(id);f.style='position:fixed;right:18px;bottom:18px;width:390px;height:650px;max-width:calc(100vw - 24px);max-height:calc(100vh - 24px);border:0;border-radius:18px;box-shadow:0 10px 40px #0003;z-index:2147483647;background:transparent';f.title='AI Website Assistant';document.body.appendChild(f)})()`}
function widgetPage(botId:string){return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial;background:transparent}.box{height:100vh;background:white;border-radius:18px;display:flex;flex-direction:column;overflow:hidden;box-shadow:0 8px 35px #0002}.head{padding:15px 17px;background:#111827;color:white;font-weight:700}.sub{font-size:11px;opacity:.7;font-weight:400;margin-top:3px}.msgs{flex:1;overflow:auto;padding:14px;background:#f8fafc}.m{max-width:85%;padding:10px 12px;border-radius:13px;margin:7px 0;line-height:1.4;font-size:14px;white-space:pre-wrap}.a{background:white;border:1px solid #e5e7eb}.u{background:#111827;color:white;margin-left:auto}.foot{padding:10px;border-top:1px solid #e5e7eb;display:flex;gap:7px}.foot input{flex:1;padding:11px;border:1px solid #d1d5db;border-radius:10px}.foot button{width:70px;border:0;border-radius:10px;background:#111827;color:white}.src{font-size:11px;margin-top:7px}.src a{color:#2563eb}</style></head><body><div class="box"><div class="head">AI Website Assistant<div class="sub">Ask about this website</div></div><div id="m" class="msgs"><div class="m a">Hi! How can I help you?</div></div><form id="f" class="foot"><input id="q" autocomplete="off" placeholder="Ask a question..."><button>Send</button></form></div><script>const bot=${JSON.stringify(botId)},m=document.getElementById('m'),q=document.getElementById('q');document.getElementById('f').onsubmit=async e=>{e.preventDefault();const v=q.value.trim();if(!v)return;add(v,'u');q.value='';const t=add('Thinking...','a');try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({botId:bot,question:v})});const j=await r.json();t.remove();add(j.answer||'I could not process that right now.','a',j.sources)}catch{t.remove();add('I could not process that right now. Please try again.','a')}};function add(x,c,s){const d=document.createElement('div');d.className='m '+c;d.textContent=x;if(s?.length){const z=document.createElement('div');z.className='src';z.innerHTML=s.map(a=>'<a target="_blank" rel="noopener" href="'+a.url.replace(/"/g,'&quot;')+'">Source</a>').join(' Â· ');d.appendChild(z)}m.appendChild(d);m.scrollTop=m.scrollHeight;return d}</script></body></html>`}

export default {async fetch(req:Request,env:Env){try{const u=new URL(req.url);if(req.method==="OPTIONS")return new Response(null,{headers:{"access-control-allow-origin":"*","access-control-allow-headers":"content-type,x-admin-key"}});if(u.pathname==="/health")return json({ok:true,service:"gen-solution",time:now()});if(u.pathname==="/"&&req.method==="GET")return new Response(html(),{headers:{"content-type":"text/html;charset=utf-8"}});if(u.pathname==="/widget.js")return new Response(widgetJs(env.PUBLIC_URL||u.origin),{headers:{"content-type":"application/javascript;charset=utf-8","cache-control":"public,max-age=300"}});if(u.pathname==="/widget")return new Response(widgetPage(u.searchParams.get("bot_id")||""),{headers:{"content-type":"text/html;charset=utf-8","content-security-policy":"default-src 'self' https:; frame-ancestors *"}});
if(u.pathname==="/api/admin/build"&&req.method==="POST"){if(!admin(req,env))return json({error:"Unauthorized"},401);const body=await req.json<any>();const seed=cleanUrl(body.url);if(!seed)return json({error:"Valid website URL required"},400);if(privateHost(hostname(seed)))return json({error:"Private/local URLs are not allowed"},400);const d=await mongo(env.MONGODB_URI);const botId=id();const job=await seedJob(d,seed,botId);const sm=await discoverSitemap(seed);if(sm.length)await d.collection<Job>("jobs").updateOne({jobId:job.jobId},{$addToSet:{queue:{$each:sm.slice(0,MAX_PAGES)}}});await buildStep(env,job.jobId);return json({ok:true,jobId:job.jobId,botId});}
if(u.pathname.startsWith('/api/admin/job/')&&req.method==="GET"){if(!admin(req,env))return json({error:"Unauthorized"},401);const jobId=u.pathname.split('/').pop()!;const j=await buildStep(env,jobId);if(!j)return json({error:"Job not found"},404);return json({jobId:j.jobId,botId:j.botId,stage:j.stage,done:j.done,pages:j.pages,pdfs:j.pdfs,chunks:j.chunks,queuedPages:j.queue.length,queuedPdfs:j.pdfQueue.length,errors:j.errors.slice(-5),embedScript:j.done?`<script src="${env.PUBLIC_URL||u.origin}/widget.js?bot_id=${j.botId}" async></script>`:null});}
if(u.pathname==="/api/chat"&&req.method==="POST"){const body=await req.json<any>();if(!body.botId||!body.question)return json({error:"botId and question required"},400);const d=await mongo(env.MONGODB_URI);const bot=await d.collection<Bot>("bots").findOne({botId:body.botId});if(!bot||bot.status!=="ready")return json({error:"Chatbot is still building"},409);return json(await answer(env,body.botId,String(body.question).slice(0,1000)));}
return new Response("Not found",{status:404});}catch(e){return json({error:String(e).slice(0,500)},500)}}};
