import { MongoClient, Db } from "mongodb";

type Env={MONGODB_URI:string;AI:any};
type Bot={botId:string;siteUrl:string;host:string;title:string;status:string;pages:number;pdfs:number;chunks:number;createdAt:string;updatedAt:string};
type Job={jobId:string;botId:string;seed:string;queue:string[];seen:string[];sitemaps:string[];sitemapSeen:string[];pdfs:string[];pages:number;chunks:number;errors:string[];done:boolean;createdAt:string;updatedAt:string};
type Chunk={botId:string;url:string;title:string;text:string;updatedAt:string};
type Pdf={botId:string;url:string;title:string;updatedAt:string};
const DB="ai_website_chatbot",MODEL="@cf/zai-org/glm-4.7-flash",UA="Gen-Solution-Bot/8.0",MAX_PAGES=400,MAX_PDFS=200,MAX_HTML=5e6,MAX_XML=2e6;
let client:MongoClient|undefined, database:Db|undefined;
const now=()=>new Date().toISOString(),id=()=>crypto.randomUUID();
const out=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*"}});
const page=(x:string,status=200)=>new Response(x,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}});
async function mongo(uri:string){if(!client){client=new MongoClient(uri,{serverSelectionTimeoutMS:8000,maxPoolSize:5});await client.connect();database=client.db(DB)}return database!}
async function indexes(d:Db){await Promise.all([d.collection("bots").createIndex({botId:1},{unique:true}).catch(()=>{}),d.collection("jobs").createIndex({jobId:1},{unique:true}).catch(()=>{}),d.collection("chunks").createIndex({botId:1,text:"text"}).catch(()=>{}),d.collection("chunks").createIndex({botId:1,url:1}).catch(()=>{}),d.collection("pdfs").createIndex({botId:1,url:1},{unique:true}).catch(()=>{})])}
function clean(raw:string,base?:string){try{const u=new URL(raw,base);if(!/^https?:$/.test(u.protocol))return null;u.hash="";u.hostname=u.hostname.toLowerCase();if(u.pathname!=="/")u.pathname=u.pathname.replace(/\/{2,}/g,"/");return u.toString().replace(/\/$/,"")}catch{return null}}
function host(u:string){return new URL(u).hostname.toLowerCase()}
function same(a:string,b:string){return host(a).replace(/^www\./,"")===host(b).replace(/^www\./,"")}
function privateHost(h:string){return /^(localhost|127\.|0\.0\.0\.0|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[0-1])\.|::1|fc|fd)/i.test(h)}
function allowed(u:string,seed:string){try{const x=new URL(u);return /^https?:$/.test(x.protocol)&&!privateHost(x.hostname)&&same(x.href,seed)}catch{return false}}
function decode(s:string){return s.replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n)).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function text(html:string){const title=decode((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim().slice(0,250);const t=decode(html.replace(/<(script|style|noscript|template|svg|canvas|iframe)[^>]*>[\s\S]*?<\/\1>/gi," ").replace(/<!--[\s\S]*?-->/g," ").replace(/<(br|\/p|\/div|\/li|\/tr|\/h[1-6]|\/section|\/article|\/header|\/footer|\/nav|\/td|\/th)[^>]*>/gi,"\n").replace(/<[^>]+>/g," ")).replace(/[\t ]+/g," ").replace(/\n\s+/g,"\n").replace(/\n{3,}/g,"\n\n").trim();return{title,text:t}}
function links(html:string,base:string,seed:string){const a=new Set<string>(),r=/<a\b[^>]*?href\s*=\s*["']([^"']+)["'][^>]*>/gi;let m:RegExpExecArray|null;while((m=r.exec(html))){const raw=m[1].trim();if(/^(mailto:|tel:|javascript:|data:|#)/i.test(raw))continue;const u=clean(raw,base);if(u&&allowed(u,seed)&&!pdf(u)&&!binary(u))a.add(u)}return [...a]}
function pdfs(html:string,base:string,seed:string){const a=new Set<string>(),r=/(?:href|data-href|data-url)\s*=\s*["']([^"']+)["']/gi;let m:RegExpExecArray|null;while((m=r.exec(html))){const u=clean(m[1],base);if(u&&allowed(u,seed)&&pdf(u))a.add(u)}return [...a]}
function pdf(u:string){return /\.pdf(?:$|[?#])/i.test(u)}
function binary(u:string){return /\.(?:jpg|jpeg|png|gif|webp|svg|ico|mp4|mp3|zip|rar|7z|doc|docx|xls|xlsx|ppt|pptx|css|js|woff2?|ttf)(?:$|[?#])/i.test(u)}
function pdfTitle(u:string){try{return decodeURIComponent(new URL(u).pathname.split("/").pop()||"PDF Document").replace(/\.pdf$/i,"").replace(/[-_]+/g," ").replace(/\s+/g," ").trim().slice(0,200)}catch{return"PDF Document"}}
function chunks(s:string){const a:string[]=[];for(let i=0;i<s.length;){let e=Math.min(i+1800,s.length),c=e<s.length?Math.max(s.lastIndexOf(" ",e),s.lastIndexOf("\n",e)):e;if(c<=i)c=e;const v=s.slice(i,c).trim();if(v.length>60)a.push(v);if(c>=s.length)break;i=Math.max(c-250,i+1)}return a}
function score(q:string,t:string){const a=new Set((q.toLowerCase().match(/[a-z0-9@._+-]+/g)||[])),b=new Set((t.toLowerCase().match(/[a-z0-9@._+-]+/g)||[]));if(!a.size)return 0;let n=0;for(const x of a)if(b.has(x))n++;return n/a.size}
async function get(url:string,xml=false){const c=new AbortController(),timer=setTimeout(()=>c.abort(),xml?8000:15000);try{const r=await fetch(url,{redirect:"follow",signal:c.signal,headers:{"user-agent":UA,accept:xml?"application/xml,text/xml,text/plain,*/*":"text/html,application/xhtml+xml,text/plain,*/*"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const n=Number(r.headers.get("content-length")||0),max=xml?MAX_XML:MAX_HTML;if(n>max)throw new Error("Response too large");const s=await r.text();if(s.length>max)throw new Error("Response too large");return{r,s}}finally{clearTimeout(timer)}}
function sitemapUrls(seed:string){return ["/sitemap.xml","/wp-sitemap.xml","/sitemap_index.xml"].map(x=>new URL(x,seed).href)}
function parseXml(s:string,seed:string){const p=new Set<string>(),sm=new Set<string>();for(const m of s.matchAll(/<loc>\s*([^<]+?)\s*<\/loc>/gi)){const u=clean(m[1].trim());if(!u||!same(u,seed))continue;if(/\.xml(?:$|[?#])/i.test(u)){sm.add(u)}else if(!pdf(u)&&!binary(u))p.add(u)}return{p:[...p],sm:[...sm]}}
async function create(env:Env,site:string){const d=await mongo(env.MONGODB_URI);await indexes(d);const botId=id(),jobId=id(),t=now();const bot:Bot={botId,siteUrl:site,host:host(site),title:"Website Assistant",status:"building",pages:0,pdfs:0,chunks:0,createdAt:t,updatedAt:t};const job:Job={jobId,botId,seed:site,queue:[site],seen:[],sitemaps:sitemapUrls(site),sitemapSeen:[],pdfs:[],pages:0,chunks:0,errors:[],done:false,createdAt:t,updatedAt:t};await d.collection("bots").insertOne(bot);await d.collection("jobs").insertOne(job);return{bot,job}}
async function step(env:Env,jobId:string){const d=await mongo(env.MONGODB_URI),jc=d.collection<Job>("jobs"),job=await jc.findOne({jobId});if(!job)throw Error("Job not found");if(job.done)return job;let did=false;if(job.sitemaps.length){const sm=job.sitemaps.shift()!;if(!job.sitemapSeen.includes(sm)){job.sitemapSeen.push(sm);try{const z=await get(sm,true),x=parseXml(z.s,job.seed);for(const u of x.p)if(job.queue.length<MAX_PAGES*2&&!job.seen.includes(u)&&!job.queue.includes(u))job.queue.push(u);for(const u of x.sm)if(job.sitemaps.length<20&&!job.sitemapSeen.includes(u)&&!job.sitemaps.includes(u))job.sitemaps.push(u)}catch(e){job.errors.push(`Sitemap: ${e instanceof Error?e.message:String(e)}`)}did=true}}else if(job.queue.length&&job.pages<MAX_PAGES){let u=job.queue.shift()!;while(u&&(job.seen.includes(u)||!allowed(u,job.seed)))u=job.queue.shift()!;if(u){job.seen.push(u);try{const z=await get(u),x=text(z.s);for(const v of links(z.s,z.r.url,job.seed))if(job.queue.length<MAX_PAGES*2&&!job.seen.includes(v)&&!job.queue.includes(v))job.queue.push(v);const ps=pdfs(z.s,z.r.url,job.seed);const col=d.collection<Pdf>("pdfs");for(const v of ps){if(!job.pdfs.includes(v)&&job.pdfs.length<MAX_PDFS)job.pdfs.push(v);await col.updateOne({botId:job.botId,url:v},{$set:{botId:job.botId,url:v,title:pdfTitle(v),updatedAt:now()}},{upsert:true})}const cc=chunks(x.text),c=d.collection<Chunk>("chunks");await c.deleteMany({botId:job.botId,url:z.r.url});if(cc.length)await c.insertMany(cc.map(v=>({botId:job.botId,url:z.r.url,title:x.title||z.r.url,text:v,updatedAt:now()})));job.pages++;job.chunks+=cc.length}catch(e){job.errors.push(`${u}: ${e instanceof Error?e.message:String(e)}`)}did=true}}
if(!did||job.pages>=MAX_PAGES||(!job.queue.length&&!job.sitemaps.length)){job.done=true;job.updatedAt=now()}job.pdfs=job.pdfs.length;job.updatedAt=now();await jc.updateOne({jobId},{$set:job});if(job.done)await d.collection("bots").updateOne({botId:job.botId},{$set:{status:"ready",pages:job.pages,pdfs:job.pdfs,chunks:job.chunks,updatedAt:now()}});return job}
async function answer(env:Env,botId:string,q:string){const d=await mongo(env.MONGODB_URI),bot=await d.collection<Bot>("bots").findOne({botId});if(!bot)throw Error("Bot not found");if(bot.status!=="ready")return{answer:"The website knowledge base is still being built. Please try again shortly.",sources:[]};let cs:Chunk[]=[];try{cs=await d.collection<Chunk>("chunks").find({botId,$text:{$search:q}}).limit(30).toArray()}catch{cs=await d.collection<Chunk>("chunks").find({botId}).limit(100).toArray()}cs=cs.map(x=>({x,s:score(q,x.text)})).sort((a,b)=>b.s-a.s).filter(x=>x.s>0).slice(0,8).map(x=>x.x);const ps=await d.collection<Pdf>("pdfs").find({botId}).limit(MAX_PDFS).toArray(),pm=ps.map(x=>({x,s:score(q,x.title+" "+x.url)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,5).map(x=>x.x);if(!cs.length&&!pm.length)return{answer:"I couldn't find that information on the website.",sources:[]};const ctx=cs.map((x,i)=>`[SOURCE ${i+1}] ${x.title}\nURL: ${x.url}\n${x.text}`).join("\n\n"),pdf=pm.map(x=>`[PDF] ${x.title}\nURL: ${x.url}`).join("\n");const prompt=`Answer ONLY from the website context. Never invent facts. If absent say exactly: I couldn't find that information on the website. PDFs are link-only; never claim to read them. Preserve phone numbers and emails exactly. English question -> English. Roman Hindi/Hinglish question -> Roman Hindi/Hinglish.\n\n${ctx}\n${pdf}\n\nQUESTION: ${q}`;const r=await env.AI.run(MODEL,{messages:[{role:"system",content:"You are a strict website-grounded assistant."},{role:"user",content:prompt}],temperature:.1,max_tokens:700});const a=String(r?.response||r?.result||r||"").trim()||"I couldn't find that information on the website.";const sources=[...new Map([...cs.map(x=>[x.url,{title:x.title||x.url,url:x.url,type:"page"}]),...pm.map(x=>[x.url,{title:x.title,url:x.url,type:"pdf"}])]).values()].slice(0,8);return{answer:a,sources}}
const esc=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");
function admin(){return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gen-Solution</title><style>body{font-family:Arial;margin:0;background:#f4f6fa;color:#111827}.wrap{max-width:820px;margin:40px auto;padding:20px}.card{background:#fff;padding:28px;border-radius:18px;box-shadow:0 10px 30px #0001}input,textarea{width:100%;box-sizing:border-box;padding:13px;margin:8px 0 15px;border:1px solid #d1d5db;border-radius:10px}button{padding:12px 18px;border:0;border-radius:10px;background:#111827;color:white;font-weight:700}.status{margin-top:18px;padding:14px;background:#f3f4f6;border-radius:10px;white-space:pre-wrap}.embed{display:none}</style></head><body><div class="wrap"><div class="card"><h1>AI Website Receptionist</h1><p>Enter the client's public website URL.</p><input id="site" placeholder="https://example.com/"><button id="build">Crawl & Build</button><div id="status" class="status">Ready.</div><div id="embed" class="embed"><p>Embed code:</p><textarea id="code" readonly></textarea><button id="copy">Copy</button></div></div></div><script>const site=document.getElementById('site'),btn=document.getElementById('build'),status=document.getElementById('status'),box=document.getElementById('embed'),code=document.getElementById('code');async function read(r,n){const t=await r.text();if(!r.ok)throw Error(n+' HTTP '+r.status+': '+t.slice(0,500));try{return JSON.parse(t)}catch{throw Error('Invalid '+n+' response: '+t.slice(0,500))}}async function run(){btn.disabled=true;box.style.display='none';try{const u=site.value.trim();if(!u)throw Error('Website URL is required.');status.textContent='Creating build job...';const b=await read(await fetch('/api/admin/build',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:u})}),'build');if(!b.ok)throw Error(b.error||'Build failed');for(;;){const s=await read(await fetch('/api/admin/job/'+encodeURIComponent(b.jobId),{cache:'no-store'}),'status');const j=s.job;status.textContent='Building...\\nPages: '+j.pages+' / 400\\nPDF links: '+j.pdfs+'\\nChunks: '+j.chunks+'\\nQueue: '+j.queue.length+'\\nSitemaps: '+j.sitemaps.length;if(j.done){status.textContent='Build completed.\\nPages: '+j.pages+'\\nPDF links: '+j.pdfs+'\\nChunks: '+j.chunks;code.value='<script src="'+location.origin+'/widget.js?bot='+encodeURIComponent(b.botId)+'" defer><\\/script>';box.style.display='block';break}await read(await fetch('/api/admin/step/'+encodeURIComponent(b.jobId),{method:'POST'}),'step');await new Promise(r=>setTimeout(r,600))}}catch(e){status.textContent='Build Error:\\n\\n'+(e instanceof Error?e.message:String(e))}finally{btn.disabled=false}}btn.addEventListener('click',run);document.getElementById('copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(code.value)}catch{code.select();document.execCommand('copy')}document.getElementById('copy').textContent='Copied!'})</script></body></html>`}
function widgetJs(url:string){const o=new URL(url).origin;return`(()=>{const s=document.currentScript;if(!s)return;const b=new URL(s.src).searchParams.get('bot');if(!b)return;const i=document.createElement('iframe');i.src=${JSON.stringify(o)}+'/widget?bot='+encodeURIComponent(b);i.title='AI Website Assistant';Object.assign(i.style,{position:'fixed',right:'18px',bottom:'18px',width:'390px',height:'620px',maxWidth:'calc(100vw - 24px)',maxHeight:'calc(100vh - 24px)',border:0,zIndex:2147483647,borderRadius:'18px',boxShadow:'0 15px 50px #0003'});document.body.appendChild(i)})()`}
async function widget(env:Env,bid:string){const d=await mongo(env.MONGODB_URI),b=await d.collection<Bot>("bots").findOne({botId:bid});if(!b)return page("Bot not found",404);return page(`<!doctype html><html><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}html,body{margin:0;height:100%;font-family:Arial}.app{height:100%;display:flex;flex-direction:column;background:#fff;border-radius:18px;overflow:hidden}.head{padding:16px;background:#111827;color:#fff;font-weight:700}.sub{font-size:12px;opacity:.7}.msgs{flex:1;overflow:auto;padding:14px;background:#f9fafb}.m{max-width:88%;padding:10px 12px;margin:0 0 10px;border-radius:12px;line-height:1.5;white-space:pre-wrap;overflow-wrap:anywhere}.bot{background:#fff;border:1px solid #e5e7eb}.user{margin-left:auto;background:#111827;color:#fff}.src{display:block;margin-top:6px;font-size:12px;color:#2563eb}.form{display:flex;gap:8px;padding:10px;border-top:1px solid #e5e7eb}input{flex:1;padding:11px;border:1px solid #d1d5db;border-radius:10px}button{border:0;border-radius:10px;background:#111827;color:#fff;padding:0 15px}</style><div class="app"><div class="head">${esc(b.title||'Website Assistant')}<div class="sub">Ask questions about this website</div></div><div id="msgs" class="msgs"><div class="m bot">Hi! How can I help you?</div></div><form id="f" class="form"><input id="q" placeholder="Ask a question..." autocomplete="off"><button>Send</button></form></div><script>const m=document.getElementById('msgs'),q=document.getElementById('q');function add(t,c,s=[]){const d=document.createElement('div');d.className='m '+c;d.textContent=t;s.forEach(x=>{const a=document.createElement('a');a.className='src';a.href=x.url;a.target='_blank';a.rel='noopener';a.textContent=(x.type==='pdf'?'PDF: ':'Source: ')+x.title;d.appendChild(a)});m.appendChild(d);m.scrollTop=m.scrollHeight}document.getElementById('f').onsubmit=async e=>{e.preventDefault();const v=q.value.trim();if(!v)return;add(v,'user');q.value='';add('Thinking...','bot');const load=m.lastElementChild;try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({botId:${JSON.stringify(bid)},question:v})});const x=await r.json();load.remove();add(x.answer||"I couldn't find that information on the website.",'bot',x.sources||[])}catch{load.textContent='Sorry, something went wrong. Please try again.'}}</script></html>`)}
export default{async fetch(req:Request,env:Env){const u=new URL(req.url),p=u.pathname;if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{"access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type"}});if(p==='/health')return out({ok:true,time:now()});if(p==='/')return page(admin());if(p==='/widget.js')return new Response(widgetJs(req.url),{headers:{'content-type':'application/javascript'}});if(p==='/widget'){const b=u.searchParams.get('bot');return b?widget(env,b):page('Missing bot',400)}if(p==='/api/admin/build'&&req.method==='POST'){try{const body=await req.json() as {url?:string};if(!body.url)return out({ok:false,error:'Website URL is required.'},400);const site=clean(body.url);if(!site||privateHost(host(site)))return out({ok:false,error:'Invalid public website URL.'},400);const x=await create(env,site);return out({ok:true,jobId:x.job.jobId,botId:x.bot.botId})}catch(e){return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}}if(p.startsWith('/api/admin/job/')&&req.method==='GET'){try{const d=await mongo(env.MONGODB_URI),j=await d.collection<Job>('jobs').findOne({jobId:p.split('/').pop()});return j?out({ok:true,job:j}):out({ok:false,error:'Job not found.'},404)}catch(e){return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}}if(p.startsWith('/api/admin/step/')&&req.method==='POST'){try{return out({ok:true,job:await step(env,p.split('/').pop()!)})}catch(e){return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}}if(p==='/api/chat'&&req.method==='POST'){try{const body=await req.json() as {botId?:string;question?:string};if(!body.botId||!body.question)return out({ok:false,error:'botId and question are required.'},400);return out({ok:true,...await answer(env,body.botId.trim(),body.question.trim())})}catch(e){return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}}return new Response('Not Found',{status:404})}};
