import { MongoClient, Db } from "mongodb";

type Env = { MONGODB_URI:string; ADMIN_KEY:string; PUBLIC_URL?:string; AI:any };
type Bot = { botId:string; siteUrl:string; host:string; title?:string; createdAt:string; updatedAt:string; status:string; pageCount:number; pdfCount:number; chunkCount:number; pdfLinks?:number };
type Chunk = { botId:string; url:string; title:string; text:string; kind:"page"; updatedAt:string };
type PdfLink = { botId:string; url:string; title:string; updatedAt:string };
type Job = { jobId:string; botId:string; seed:string; queue:string[]; visited:string[]; pdfLinks:string[]; pdfDone:string[]; stage:string; pages:number; pdfs:number; chunks:number; errors:string[]; createdAt:string; updatedAt:string; done:boolean; sitemapLoaded?:boolean };

const DB_NAME="ai_website_chatbot";
const MAX_PAGES=400;
const MAX_PDFS=200;
const PAGE_BATCH=1;
const MAX_CHUNK=1800;
const OVERLAP=250;
const MAX_HTML_BYTES=5_000_000;
const MODEL="@cf/zai-org/glm-4.7-flash";
const UA="Gen-Solution-Bot/5.0";

let client:MongoClient|undefined;
let db:Db|undefined;

function now(){return new Date().toISOString()}
function id(){return crypto.randomUUID()}
function json(x:any,status=200){return new Response(JSON.stringify(x),{status,headers:{"content-type":"application/json; charset=utf-8","access-control-allow-origin":"*","access-control-allow-headers":"content-type,x-admin-key"}})}
function admin(req:Request,env:Env){const key=req.headers.get("x-admin-key"); const q=new URL(req.url).searchParams.get("key"); return !!env.ADMIN_KEY && (key===env.ADMIN_KEY||q===env.ADMIN_KEY)}
async function mongo(uri:string){if(!client){client=new MongoClient(uri,{serverSelectionTimeoutMS:8000,maxPoolSize:5});await client.connect();db=client.db(DB_NAME)}return db!}
function cleanUrl(raw:string,base?:string){try{const u=new URL(raw,base);if(!/^https?:$/.test(u.protocol))return null;u.hash="";u.hostname=u.hostname.toLowerCase();if(u.pathname!=="/")u.pathname=u.pathname.replace(/\/{2,}/g,"/");return u.toString().replace(/\/$/,"")}catch{return null}}
function host(url:string){return new URL(url).hostname.toLowerCase()}
function sameHost(a:string,b:string){const x=host(a),y=host(b);return x===y}
function privateHost(h:string){return /^(localhost|127\.|0\.0\.0\.0|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[0-1])\.|::1|fc|fd)/i.test(h)}
function allowed(url:string,seed:string){try{const u=new URL(url);return /^https?:$/.test(u.protocol)&&!privateHost(u.hostname)&&sameHost(u.href,seed)}catch{return false}}
function decode(s:string){return s.replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function stripHtml(html:string){
  const title=decode((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim().slice(0,300);
  const cleaned=html.replace(/<(script|style|noscript|template|svg|canvas|iframe)[^>]*>[\s\S]*?<\/\1>/gi," ").replace(/<!--[\s\S]*?-->/g," ");
  const withBreaks=cleaned.replace(/<(br|\/p|\/div|\/li|\/tr|\/h[1-6]|\/section|\/article|\/header|\/footer|\/nav|\/td|\/th)[^>]*>/gi,"\n");
  const text=decode(withBreaks.replace(/<[^>]+>/g," ")).replace(/[\t ]+/g," ").replace(/\n\s+/g,"\n").replace(/\n{3,}/g,"\n\n").trim();
  return {title,text};
}
function extractLinks(html:string,base:string,seed:string){
  const out=new Set<string>();
  const re=/<a\b[^>]*?href\s*=\s*["']([^"']+)["'][^>]*>/gi;let m;
  while((m=re.exec(html))){const raw=m[1].trim();if(/^(mailto:|tel:|javascript:|data:|#)/i.test(raw))continue;const u=cleanUrl(raw,base);if(u&&allowed(u,seed)&&!isBinary(u))out.add(u)}
  return [...out];
}
function extractPdfLinks(html:string,base:string,seed:string){
  const out=new Set<string>();
  const re=/(?:href|data-href|data-url)\s*=\s*["']([^"']+)["']/gi;let m;
  while((m=re.exec(html))){const u=cleanUrl(m[1],base);if(u&&allowed(u,seed)&&isPdfUrl(u))out.add(u)}
  return [...out];
}
function isPdfUrl(u:string){return /\.pdf(?:$|[?#])/i.test(u)}
function isBinary(u:string){return /\.(?:jpg|jpeg|png|gif|webp|svg|ico|mp4|mp3|zip|rar|7z|doc|docx|xls|xlsx|ppt|pptx|css|js|woff2?|ttf)(?:$|[?#])/i.test(u)}
function chunkText(text:string){const out:string[]=[];let i=0;while(i<text.length){const end=Math.min(text.length,i+MAX_CHUNK);let cut=end;if(end<text.length){const p=Math.max(text.lastIndexOf(" ",end),text.lastIndexOf("\n",end));if(p>i+800)cut=p}const t=text.slice(i,cut).trim();if(t.length>60)out.push(t);if(cut>=text.length)break;i=Math.max(cut-OVERLAP,i+1)}return out}
function tokens(s:string){return new Set((s.toLowerCase().match(/[a-z0-9@._+-]+/g)||[]).filter(x=>x.length>1))}
function lexicalScore(q:string,t:string){const a=tokens(q),b=tokens(t);if(!a.size||!b.size)return 0;let hit=0;for(const x of a)if(b.has(x))hit++;return hit/a.size}
async function fetchPage(url:string,seed:string){if(!allowed(url,seed))throw new Error("blocked URL");const c=new AbortController();const timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{redirect:"follow",signal:c.signal,headers:{"user-agent":UA,"accept":"text/html,application/xhtml+xml,text/plain;q=0.9,*/*;q=0.1","accept-language":"en-US,en;q=0.8"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);if(!allowed(r.url||url,seed))throw new Error("redirected outside website");return r}finally{clearTimeout(timer)}}
async function ensureIndexes(d:Db){const c=d.collection("chunks");await c.createIndex({botId:1,updatedAt:-1}).catch(()=>{});await c.createIndex({botId:1,text:"text"}).catch(()=>{});await d.collection("pdfLinks").createIndex({botId:1,url:1},{unique:true}).catch(()=>{});await d.collection("bots").createIndex({botId:1},{unique:true}).catch(()=>{});await d.collection("jobs").createIndex({jobId:1},{unique:true}).catch(()=>{})}

async function sitemapUrls(seed:string){
  const candidates=[new URL("/sitemap.xml",seed).href,new URL("/wp-sitemap.xml",seed).href];
  const discovered=new Set<string>();const queue=[...candidates];const seen=new Set<string>();
  try{const r=await fetch(candidates[0],{headers:{"user-agent":UA}});if(r.ok){const text=await r.text();for(const x of [...text.matchAll(/<loc>\s*([^<]+?)\s*<\/loc>/gi)]){const u=cleanUrl(x[1]);if(u&&sameHost(u,seed))queue.push(u)}}}catch{}
  try{const r=await fetch(candidates[1],{headers:{"user-agent":UA}});if(r.ok){const text=await r.text();for(const x of [...text.matchAll(/<loc>\s*([^<]+?)\s*<\/loc>/gi)]){const u=cleanUrl(x[1]);if(u&&sameHost(u,seed))queue.push(u)}}}catch{}
  while(queue.length&&discovered.size<MAX_PAGES*3){const s=queue.shift()!;if(seen.has(s))continue;seen.add(s);try{const r=await fetch(s,{headers:{"user-agent":UA}});if(!r.ok)continue;const t=await r.text();for(const x of [...t.matchAll(/<loc>\s*([^<]+?)\s*<\/loc>/gi)]){const u=cleanUrl(x[1]);if(!u||!sameHost(u,seed))continue;if(/sitemap/i.test(u)&&/\.xml(?:$|[?#])/i.test(u))queue.push(u);else if(isPdfUrl(u)){}else discovered.add(u)}}catch{}}
  return [...discovered].slice(0,MAX_PAGES);
}
async function robotsSitemaps(seed:string){try{const u=new URL("/robots.txt",seed);const r=await fetch(u.href,{headers:{"user-agent":UA}});if(!r.ok)return [];const t=await r.text();return t.split(/\r?\n/).filter(x=>/^\s*sitemap\s*:/i.test(x)).map(x=>cleanUrl(x.replace(/^\s*sitemap\s*:/i,""))).filter((x):x is string=>!!x&&sameHost(x,seed)).slice(0,20)}catch{return []}}

async function seedJob(d:Db,seed:string,botId:string){const u=new URL(seed);const bot:Bot={botId,siteUrl:seed,host:u.hostname,title:"",createdAt:now(),updatedAt:now(),status:"building",pageCount:0,pdfCount:0,chunkCount:0,pdfLinks:0};await d.collection("bots").updateOne({botId},{$set:bot},{upsert:true});await d.collection("chunks").deleteMany({botId});await d.collection("pdfLinks").deleteMany({botId});const job:Job={jobId:id(),botId,seed,queue:[seed],visited:[],pdfLinks:[],pdfDone:[],stage:"crawling",pages:0,pdfs:0,chunks:0,errors:[],createdAt:now(),updatedAt:now(),done:false,sitemapLoaded:false};await d.collection("jobs").insertOne(job);return job}

async function crawlStep(job:Job,d:Db){
  const urls=job.queue.splice(0,PAGE_BATCH);if(!urls.length){job.stage="done";return}
  for(const url of urls){if(job.visited.includes(url))continue;job.visited.push(url);try{
    const r=await fetchPage(url,job.seed);const ct=(r.headers.get("content-type")||"").toLowerCase();if(isPdfUrl(url)||ct.includes("application/pdf")){if(!job.pdfLinks.includes(url)&&job.pdfLinks.length<MAX_PDFS)job.pdfLinks.push(url);continue}
    const len=Number(r.headers.get("content-length")||0);if(len>MAX_HTML_BYTES)throw new Error("HTML page too large");const raw=await r.text();if(raw.length>MAX_HTML_BYTES)throw new Error("HTML page too large");
    const htmlish=ct.includes("html")||ct.includes("text/plain")||/<(?:html|body|main|article|nav|header)\b/i.test(raw.slice(0,50000));if(!htmlish)continue;
    const {title,text}=stripHtml(raw);const parts=chunkText(text);if(parts.length){await d.collection("chunks").insertMany(parts.map(p=>({botId:job.botId,url:r.url||url,title,text:p,kind:"page",updatedAt:now()})));job.chunks+=parts.length;job.pages++;await d.collection("bots").updateOne({botId:job.botId},{$set:{title:title||undefined},$inc:{pageCount:1,chunkCount:parts.length}})}
    for(const p of extractPdfLinks(raw,r.url||url,job.seed))if(!job.pdfLinks.includes(p)&&job.pdfLinks.length<MAX_PDFS)job.pdfLinks.push(p);
    const found=extractLinks(raw,r.url||url,job.seed);const queued=new Set([...job.queue,...job.visited]);for(const u of found)if(!queued.has(u)&&job.queue.length<MAX_PAGES*2){job.queue.push(u);queued.add(u)}
  }catch(e){if(job.errors.length<50)job.errors.push(`${url}: ${String(e).slice(0,220)}`)}}
  if(!job.sitemapLoaded){job.sitemapLoaded=true;const sm=[...(await robotsSitemaps(job.seed)),...(await sitemapUrls(job.seed))];const seen=new Set([...job.queue,...job.visited]);for(const u of sm)if(!seen.has(u)&&job.queue.length<MAX_PAGES*2){job.queue.push(u);seen.add(u)}}
  job.pdfLinks=[...new Set(job.pdfLinks)].slice(0,MAX_PDFS);if(job.queue.length===0)job.stage="done";job.updatedAt=now();await d.collection("jobs").updateOne({jobId:job.jobId},{$set:job});await d.collection("bots").updateOne({botId:job.botId},{$set:{pdfLinks:job.pdfLinks.length}})
}
async function finalize(job:Job,d:Db){job.done=true;job.stage="done";job.updatedAt=now();await d.collection("jobs").updateOne({jobId:job.jobId},{$set:job});await d.collection("bots").updateOne({botId:job.botId},{$set:{status:job.pages||job.chunks?"ready":"failed",updatedAt:now(),pageCount:job.pages,pdfCount:0,chunkCount:job.chunks,pdfLinks:job.pdfLinks.length}})}
async function buildStep(env:Env,jobId:string){const d=await mongo(env.MONGODB_URI);await ensureIndexes(d);const job=await d.collection<Job>("jobs").findOne({jobId});if(!job||job.done)return job;if(job.stage==="crawling")await crawlStep(job,d);if(job.stage==="done")await finalize(job,d);else await d.collection("jobs").updateOne({jobId},{$set:{updatedAt:now()}});return job}

async function answer(env:Env,botId:string,q:string){const d=await mongo(env.MONGODB_URI);await ensureIndexes(d);const c=d.collection<Chunk>("chunks");let candidates:any[]=[];try{candidates=await c.find({botId,$text:{$search:q}},{projection:{_id:0}}).sort({score:{$meta:"textScore"}}).limit(40).toArray()}catch{candidates=await c.find({botId},{projection:{_id:0}}).limit(200).toArray()}candidates=candidates.map(x=>({...x,_score:lexicalScore(q,x.text)})).sort((a,b)=>b._score-a._score).slice(0,8);if(!candidates.length||candidates[0]._score<0.08)return {answer:"I couldn't find that information on the website.",sources:[]};const context=candidates.map((x,i)=>`SOURCE ${i+1}\nURL: ${x.url}\nCONTENT:\n${x.text}`).join("\n\n");const system=`You are the AI receptionist for the website represented by the supplied sources. Answer ONLY from those sources. Never use outside knowledge or invent facts. Do not guess dates, fees, eligibility, names, phone numbers, emails, policies, or availability. If the answer is not supported by the sources, say exactly: "I couldn't find that information on the website." If the user writes natural Roman Hinglish, reply in natural Roman Hinglish; otherwise reply in English. Be concise. If the sources contain a relevant official PDF/document link but not its contents, tell the user where to open/download it instead of inventing its contents.`;const res=await env.AI.run(MODEL,{messages:[{role:"system",content:system},{role:"user",content:`WEBSITE SOURCES:\n${context}\n\nUSER QUESTION: ${q}`}],max_tokens:500,temperature:0.1});const text=typeof res==="string"?res:(res?.response||res?.result?.response||"");return {answer:text||"I couldn't find that information on the website.",sources:[...new Map(candidates.map(x=>[x.url,{url:x.url,title:x.title}])).values()].slice(0,5)}}

function adminHtml(){return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gen Solution</title><style>body{font-family:Inter,Arial,sans-serif;background:#f5f7fb;margin:0;color:#111827}.wrap{max-width:900px;margin:50px auto;padding:24px}.card{background:#fff;border-radius:18px;padding:28px;box-shadow:0 8px 35px #0001}input,button{width:100%;box-sizing:border-box;padding:13px;border-radius:10px;border:1px solid #d1d5db;font-size:15px}button{margin-top:12px;background:#111827;color:#fff;border:0;cursor:pointer}.status{margin-top:18px;padding:15px;background:#f3f4f6;border-radius:10px;white-space:pre-wrap;overflow:auto}.small{color:#6b7280;font-size:13px;margin-top:10px}</style></head><body><div class="wrap"><div class="card"><h1>Gen Solution</h1><p>Build a website-only AI receptionist.</p><input id="url" placeholder="https://example.com"><input id="key" placeholder="Admin key" type="password" style="margin-top:10px"><button onclick="build()">Crawl & Build</button><div id="s" class="status">Ready.</div></div></div><script>async function build(){const u=document.getElementById('url').value.trim(),k=document.getElementById('key').value,s=document.getElementById('s');s.textContent='Starting...';try{const r=await fetch('/api/admin/build',{method:'POST',headers:{'content-type':'application/json','x-admin-key':k},body:JSON.stringify({url:u})});const j=await r.json();if(!r.ok){s.textContent=j.error||'Failed';return}let timer=setInterval(async()=>{try{const x=await fetch('/api/admin/job/'+j.jobId,{headers:{'x-admin-key':k}});const z=await x.json();s.textContent=JSON.stringify(z,null,2);if(z.done)clearInterval(timer)}catch(e){s.textContent=String(e)}},1000)}catch(e){s.textContent=String(e)}}}</script></body></html>`}
function widgetJs(publicUrl:string){return `(()=>{const s=document.currentScript,u=new URL(s.src),id=u.searchParams.get('bot_id')||'';const f=document.createElement('iframe');f.src=${JSON.stringify(publicUrl)}+'/widget?bot_id='+encodeURIComponent(id);Object.assign(f.style,{position:'fixed',right:'18px',bottom:'18px',width:'390px',height:'650px',maxWidth:'calc(100vw - 24px)',maxHeight:'calc(100vh - 24px)',border:'0',borderRadius:'18px',boxShadow:'0 10px 40px #0003',zIndex:'2147483647',background:'transparent'});f.title='AI Website Assistant';document.body.appendChild(f)})()`}
function widgetPage(botId:string){return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:transparent}.box{height:100vh;background:#fff;border-radius:18px;display:flex;flex-direction:column;overflow:hidden;box-shadow:0 8px 35px #0002}.head{padding:15px 17px;background:#111827;color:#fff;font-weight:700}.sub{font-size:11px;opacity:.7;font-weight:400;margin-top:3px}.msgs{flex:1;overflow:auto;padding:14px;background:#f8fafc}.m{max-width:85%;padding:10px 12px;border-radius:13px;margin:7px 0;line-height:1.45;font-size:14px;white-space:pre-wrap}.a{background:#fff;border:1px solid #e5e7eb}.u{background:#111827;color:#fff;margin-left:auto}.foot{padding:10px;border-top:1px solid #e5e7eb;display:flex;gap:7px}.foot input{flex:1;padding:11px;border:1px solid #d1d5db;border-radius:10px;outline:0}.foot button{width:70px;border:0;border-radius:10px;background:#111827;color:#fff}.src{font-size:11px;margin-top:7px}.src a{color:#2563eb}</style></head><body><div class="box"><div class="head">AI Website Assistant<div class="sub">Ask about this website</div></div><div id="m" class="msgs"><div class="m a">Hi! How can I help you?</div></div><form id="f" class="foot"><input id="q" autocomplete="off" placeholder="Ask a question..."><button>Send</button></form></div><script>const bot=${JSON.stringify(botId)},m=document.getElementById('m'),q=document.getElementById('q');document.getElementById('f').onsubmit=async e=>{e.preventDefault();const v=q.value.trim();if(!v)return;add(v,'u');q.value='';const t=add('Thinking...','a');try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({botId:bot,question:v})});const j=await r.json();t.remove();add(j.answer||'I could not process that right now.','a',j.sources)}catch{t.remove();add('I could not process that right now. Please try again.','a')}};function add(x,c,s){const d=document.createElement('div');d.className='m '+c;d.textContent=x;if(s?.length){const z=document.createElement('div');z.className='src';s.forEach(a=>{const l=document.createElement('a');l.href=a.url;l.target='_blank';l.rel='noopener';l.textContent=a.title||'Source';z.appendChild(l);z.appendChild(document.createTextNode(' · '))});d.appendChild(z)}m.appendChild(d);m.scrollTop=m.scrollHeight;return d}</script></body></html>`}

export default {async fetch(req:Request,env:Env){try{const u=new URL(req.url);if(req.method==="OPTIONS")return new Response(null,{headers:{"access-control-allow-origin":"*","access-control-allow-headers":"content-type,x-admin-key"}});if(u.pathname==="/health")return json({ok:true,service:"gen-solution",version:"5.0",time:now()});if(u.pathname==="/"&&req.method==="GET")return new Response(adminHtml(),{headers:{"content-type":"text/html;charset=utf-8"}});if(u.pathname==="/widget.js")return new Response(widgetJs(env.PUBLIC_URL||u.origin),{headers:{"content-type":"application/javascript;charset=utf-8","cache-control":"public,max-age=300"}});if(u.pathname==="/widget")return new Response(widgetPage(u.searchParams.get("bot_id")||""),{headers:{"content-type":"text/html;charset=utf-8","content-security-policy":"default-src 'self' https:; frame-ancestors *"}});
if(u.pathname==="/api/admin/build"&&req.method==="POST"){if(!admin(req,env))return json({error:"Unauthorized"},401);const body=await req.json<any>();const seed=cleanUrl(body.url);if(!seed)return json({error:"Valid website URL required"},400);if(privateHost(host(seed)))return json({error:"Private/local URLs are not allowed"},400);const d=await mongo(env.MONGODB_URI);await ensureIndexes(d);const botId=id();const job=await seedJob(d,seed,botId);await buildStep(env,job.jobId);return json({ok:true,jobId:job.jobId,botId});}
if(u.pathname.startsWith('/api/admin/job/')&&req.method==="GET"){if(!admin(req,env))return json({error:"Unauthorized"},401);const jobId=u.pathname.slice('/api/admin/job/'.length);const j=await buildStep(env,jobId);if(!j)return json({error:"Job not found"},404);return json({jobId:j.jobId,botId:j.botId,stage:j.stage,done:j.done,pages:j.pages,pdfs:0,chunks:j.chunks,queuedPages:j.queue.length,queuedPdfs:0,pdfLinks:j.pdfLinks.length,errors:j.errors.slice(-8),embedScript:j.done?`<script src="${env.PUBLIC_URL||u.origin}/widget.js?bot_id=${j.botId}" async></script>`:null});}
if(u.pathname==="/api/chat"&&req.method==="POST"){const body=await req.json<any>();if(!body.botId||!body.question)return json({error:"botId and question required"},400);const d=await mongo(env.MONGODB_URI);const bot=await d.collection<Bot>("bots").findOne({botId:body.botId});if(!bot||bot.status!=="ready")return json({error:"Chatbot is still building"},409);return json(await answer(env,body.botId,String(body.question).slice(0,1000)));}
if(u.pathname==="/api/admin/pdfs"&&req.method==="GET"){if(!admin(req,env))return json({error:"Unauthorized"},401);const botId=u.searchParams.get('bot_id');if(!botId)return json({error:"bot_id required"},400);const d=await mongo(env.MONGODB_URI);return json({pdfs:await d.collection<PdfLink>('pdfLinks').find({botId},{projection:{_id:0}}).sort({title:1}).limit(MAX_PDFS).toArray()});}
return new Response("Not found",{status:404});}catch(e){return json({error:String(e).slice(0,500)},500)}}};
